
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jul 04 20:10:49 CST 2017
//----------------------------------------------------

package tarea4_5;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int parDer = 4;
  public static final int parIzq = 3;
  public static final int num = 5;
  public static final int error = 1;
  public static final int coma = 2;
  public static final int EOF = 0;
}

